### ISSUE TITLE
this.requestMatcher 里面没有/login/sms /login/email 这些URL直接报404

### ISSUE THREAD

**Issue by admintertar** [vains-Sofia/oauth2-security-spring-boot-starter#1]
endpointsMatcher 似乎是已经写死不能单独新增端点的 这怎么破

![image](https://github.com/user-attachments/assets/1039f63d-ba53-4e33-a2b4-1f71283a304b)

**Comment by admintertar** [comment]
![image](https://github.com/user-attachments/assets/6cc51cb0-ac9d-440b-a4b3-91f51d2e4130)

需要单独配置多个SecurityFilterChain。。。。不要和authorizationServerSecurity的冲突....

**Comment by vains-Sofia** [comment]
牛啊，刚收到邮件时我还寻思咋整呢
